version: '3.9'

services:

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Europe/Moscow
      ADMINS: ${ADMINS}
      BOT_TOKEN: ${BOT_TOKEN}
      PROXY_LOGIN: ${PROXY_LOGIN}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PG_NAME: gino
      PG_USER: postgres
      PG_HOST: postgres
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
    volumes:
     - .:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: >
      --requirepass ${REDIS_PASSWORD}
    environment:
      TZ: Europe/Moscow
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: on-failure

  postgres:
    image: postgres:alpine
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: gino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../pg Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    restart: on-failure