"""adding indexes

Revision ID: 6131a8840662
Revises: ed233dc913af
Create Date: 2022-10-01 14:30:38.472553

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6131a8840662'
down_revision = 'ed233dc913af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('group_idx_name', 'group', ['name'])
    op.add_column('main_schedule_info', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('start_date', sa.Date(), default=sa.func.current_date()))
    op.create_index('main_schedule_info_idx_user_id', 'main_schedule_info', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('main_schedule_info_idx_user_id', table_name='main_schedule_info')
    op.drop_column('user', 'start_date')
    op.drop_column('main_schedule_info', 'name')
    op.drop_index('group_idx_name', table_name='group')
    # ### end Alembic commands ###
