"""Init

Revision ID: b351ee68c259
Revises: 
Create Date: 2023-02-22 12:07:18.715553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b351ee68c259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tt_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index('group_idx_name', 'group', ['name'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('main_schedule_info',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('user_type_is_student', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_index('main_schedule_info_idx_user_id', 'main_schedule_info', ['user_id'], unique=True)
    op.create_table('settings',
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_summary', sa.Time(), nullable=True),
    sa.Column('notification_of_lesson', sa.Time(), nullable=True),
    sa.Column('schedule_view_is_picture', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('settings_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index('main_schedule_info_idx_user_id', table_name='main_schedule_info')
    op.drop_table('main_schedule_info')
    op.drop_table('user')
    op.drop_index('group_idx_name', table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
