"""first migration

Revision ID: 9474559c591d
Revises: 
Create Date: 2022-09-24 12:28:54.580993

"""

# revision identifiers, used by Alembic.
revision = '9474559c591d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
