"""language of user in settings

Revision ID: 9bea9b771933
Revises: 9474559c591d
Create Date: 2022-09-24 12:37:05.687082

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9bea9b771933'
down_revision = '9474559c591d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('language', sa.String(length=2), nullable=True))
    op.execute('UPDATE settings SET language = (SELECT language FROM "user" WHERE user_id = settings.user_id);')
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=10), nullable=True))
    op.execute('UPDATE "user" SET language = (SELECT language FROM settings WHERE user_id = "user".user_id);')
    op.drop_column('settings', 'language')
    # ### end Alembic commands ###
