from . import start
from . import help
from . import settings
from . import user_status
from . import choice_teacher
from . import timetable
from . import student_navigation
from . import educator
from . import group
from . import choice_group
